//! PWA plumbing for the phone surface (PLAN v2 **D6**, task **T2.2**).
//!
//! Three things live here, and they are deliberately together because they
//! are one contract:
//!
//! 1. [`MANIFEST_JSON`] — the web app manifest, served from **root** at
//!    `/manifest.webmanifest` with `scope: "/"` and `start_url: "/m"`. G6/R-16
//!    was that the v1 manifest went out from a hashed `asset!()` path under
//!    `/assets/`, which puts `start_url` *outside* the manifest's own scope
//!    and makes the install prompt impossible however many icons it lists.
//!    Nothing in this file may ever acquire a content hash for that reason.
//! 2. [`SERVICE_WORKER_JS`] — `sw.js`, `include_str!`'d from the file next to
//!    this one (`docs/NON_RUST.md` declares it) and served from root so its
//!    default scope is `/`.
//! 3. [`ICONS`] — the T0.7 icon set, `include_bytes!`'d into the binary and
//!    served from stable `/icons/<name>.png` URLs. Embedding them rather than
//!    pointing the manifest at `asset!()` output keeps the manifest hash-free
//!    (see 1) *and* means an install can never fail because a `dx build` step
//!    did not copy a file.
//!
//! Registration itself is [`register_service_worker`], called once by
//! [`super::MobileShell`] via `web_sys`.

/// The web app manifest, byte for byte.
///
/// Hand-written Rust rather than an included `.json` so the whole PWA
/// surface stays inside the Rust stack (only `sw.js` is a declared non-Rust
/// component). Every field the T2.2 acceptance test reads —
/// `scope`, `start_url`, `display`, `icons[].purpose` — is asserted in
/// `tests/pwa_tests.rs`.
pub const MANIFEST_JSON: &str = r##"{
  "id": "/m",
  "name": "Sheffield Family Hub",
  "short_name": "Family Hub",
  "description": "Morning routines, the family calendar, the whiteboard and the TV remote.",
  "scope": "/",
  "start_url": "/m",
  "display": "standalone",
  "display_override": ["standalone", "minimal-ui"],
  "orientation": "portrait-primary",
  "background_color": "#FDFDFD",
  "theme_color": "#2672B3",
  "lang": "en",
  "dir": "ltr",
  "icons": [
    {
      "src": "/icons/icon-192.png",
      "sizes": "192x192",
      "type": "image/png",
      "purpose": "any"
    },
    {
      "src": "/icons/icon-512.png",
      "sizes": "512x512",
      "type": "image/png",
      "purpose": "any"
    },
    {
      "src": "/icons/icon-192-maskable.png",
      "sizes": "192x192",
      "type": "image/png",
      "purpose": "maskable"
    },
    {
      "src": "/icons/icon-512-maskable.png",
      "sizes": "512x512",
      "type": "image/png",
      "purpose": "maskable"
    }
  ]
}
"##;

/// The manifest's canonical, hash-free URL (PLAN v2 D6 / R-16).
pub const MANIFEST_PATH: &str = "/manifest.webmanifest";
/// The service worker's canonical, hash-free URL. Root-served so its default
/// registration scope is `/`, which is what `scope: "/"` in the manifest
/// requires.
pub const SERVICE_WORKER_PATH: &str = "/sw.js";
/// `Content-Type` browsers require before they will treat the manifest as one.
pub const MANIFEST_CONTENT_TYPE: &str = "application/manifest+json";
/// `Content-Type` for `sw.js`. A service worker served as anything but a
/// JavaScript MIME type is rejected outright by every browser.
pub const SERVICE_WORKER_CONTENT_TYPE: &str = "text/javascript";

/// `sw.js`, compiled into the binary (`docs/NON_RUST.md`, PLAN v2 D6:
/// "`sw.js` ≈ 40 lines from `include_str!`").
pub const SERVICE_WORKER_JS: &str = include_str!("sw.js");

/// The PWA icon set generated by T0.7's `xtask`, embedded so the install
/// prompt can never be blocked by a missing file.
pub const ICONS: [(&str, &[u8]); 4] = [
    (
        "icon-192.png",
        include_bytes!("../../../../assets/icons/icon-192.png"),
    ),
    (
        "icon-512.png",
        include_bytes!("../../../../assets/icons/icon-512.png"),
    ),
    (
        "icon-192-maskable.png",
        include_bytes!("../../../../assets/icons/icon-192-maskable.png"),
    ),
    (
        "icon-512-maskable.png",
        include_bytes!("../../../../assets/icons/icon-512-maskable.png"),
    ),
];

/// The bytes of the embedded icon called `name`, or `None`.
///
/// Deliberately an exact-name lookup against a fixed table rather than a
/// filesystem read: `/icons/<file>` is a user-supplied path segment, and a
/// table lookup cannot be walked out of with `..`.
pub fn icon_bytes(name: &str) -> Option<&'static [u8]> {
    ICONS
        .iter()
        .find(|(icon_name, _)| *icon_name == name)
        .map(|(_, bytes)| *bytes)
}

/// Is `url` inside `scope`? (R-16.)
///
/// The manifest algorithm is a path-prefix match on the same origin, with the
/// scope treated as ending at a path segment boundary — so `/m` is inside
/// `/`, and inside `/m`, but `/mobile` is **not** inside `/m/`. This is the
/// exact rule that made the v1 manifest uninstallable: served from a hashed
/// `/assets/…` URL, its implicit scope was `/assets/`, which does not contain
/// `start_url: "/m"`, so the browser rejected the manifest outright.
pub fn path_is_within_scope(scope: &str, url: &str) -> bool {
    if scope == "/" {
        return url.starts_with('/');
    }
    let scope = scope.strip_suffix('/').unwrap_or(scope);
    url == scope || url.starts_with(&format!("{scope}/"))
}

/// Does `path` look like it carries a build-time content hash?
///
/// A cheap, deliberate heuristic: any run of eight or more hexadecimal
/// characters. `dx`'s `asset!()` output (`…-dx<16 hex>.json`) trips it;
/// `/manifest.webmanifest`, `/sw.js` and `/icons/icon-192.png` do not. It
/// exists so `tests/pwa_tests.rs` can fail loudly if anyone ever routes the
/// manifest or the service worker back through the asset pipeline and
/// silently re-breaks installability (G6).
pub fn contains_content_hash(path: &str) -> bool {
    let mut run = 0usize;
    for ch in path.chars() {
        if ch.is_ascii_hexdigit() {
            run += 1;
            if run >= 8 {
                return true;
            }
        } else {
            run = 0;
        }
    }
    false
}

// ---------------------------------------------------------------------------
// Registration (browser side)
// ---------------------------------------------------------------------------

/// Register `/sw.js` with the browser. Idempotent — the browser dedupes a
/// repeat registration of the same script URL and scope, so calling this on
/// every mount of the phone shell is safe.
///
/// Silent no-op when there is no service worker container: the TV origin is
/// plain HTTP (D3′) and therefore not a secure context, and iOS Safari
/// without the CA installed is in the same position. The phone surface has to
/// keep working without a service worker; it only loses offline caching.
#[cfg(all(feature = "web", target_arch = "wasm32"))]
pub fn register_service_worker() {
    let Some(window) = web_sys::window() else {
        return;
    };
    let container = window.navigator().service_worker();
    // The returned promise is intentionally dropped: registration failures
    // (insecure context, user has disabled service workers) are not fatal and
    // there is nothing useful to show the user about them.
    let _ = container.register(SERVICE_WORKER_PATH);
}

/// SSR / non-wasm build: nothing to register.
#[cfg(not(all(feature = "web", target_arch = "wasm32")))]
pub fn register_service_worker() {}

// ---------------------------------------------------------------------------
// Serving (server side)
// ---------------------------------------------------------------------------

/// The three root routes' axum handlers.
///
/// They live here, next to the bytes they serve, and `server::router` only
/// wires them up — the seam `src/server/router.rs`'s own T0.6 doc comment
/// reserved for this task ("T2.2 replaces the body with the real manifest …
/// but keeps this route and its content type").
#[cfg(feature = "server")]
pub mod handlers {
    use axum::http::header;
    use axum::response::{IntoResponse, Response};

    /// `GET /manifest.webmanifest`.
    pub async fn manifest() -> impl IntoResponse {
        (
            [(header::CONTENT_TYPE, super::MANIFEST_CONTENT_TYPE)],
            super::MANIFEST_JSON,
        )
    }

    /// `GET /sw.js`.
    ///
    /// `Cache-Control: no-cache` is what lets a redeployed hub actually
    /// replace its own service worker: browsers revalidate the script on
    /// every navigation, and a cached copy would pin the old one for up to
    /// 24 hours.
    pub async fn service_worker() -> impl IntoResponse {
        (
            [
                (header::CONTENT_TYPE, super::SERVICE_WORKER_CONTENT_TYPE),
                (header::CACHE_CONTROL, "no-cache"),
                // Not one of `http`'s pre-defined constants, but the header
                // that lets a root-scoped worker be served from anywhere if
                // the path ever moves.
                (
                    header::HeaderName::from_static("service-worker-allowed"),
                    "/",
                ),
            ],
            super::SERVICE_WORKER_JS,
        )
    }

    /// `GET /icons/{file}` — the embedded PWA icon set.
    pub async fn icon(axum::extract::Path(file): axum::extract::Path<String>) -> Response {
        match super::icon_bytes(&file) {
            Some(bytes) => (
                [
                    (header::CONTENT_TYPE, "image/png"),
                    // Content is baked into the binary, so a long cache is
                    // safe: a new build is a new binary.
                    (header::CACHE_CONTROL, "public, max-age=604800"),
                ],
                bytes,
            )
                .into_response(),
            None => (axum::http::StatusCode::NOT_FOUND, "no such icon\n").into_response(),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_manifest_is_valid_json_with_a_root_scope_and_a_phone_start_url() {
        let manifest: serde_json::Value =
            serde_json::from_str(MANIFEST_JSON).expect("the manifest must be valid JSON");
        assert_eq!(manifest["scope"], "/");
        assert_eq!(manifest["start_url"], "/m");
        assert_eq!(manifest["display"], "standalone");
    }

    #[test]
    fn every_manifest_icon_resolves_to_an_embedded_file() {
        let manifest: serde_json::Value =
            serde_json::from_str(MANIFEST_JSON).expect("the manifest must be valid JSON");
        let icons = manifest["icons"].as_array().expect("icons is an array");
        assert!(icons.len() >= 2, "at least two icons are required");

        for icon in icons {
            let src = icon["src"].as_str().expect("every icon has a src");
            let name = src
                .strip_prefix("/icons/")
                .unwrap_or_else(|| panic!("{src} must be served from the root /icons/ path"));
            assert!(
                icon_bytes(name).is_some(),
                "{src} is listed in the manifest but not embedded in the binary"
            );
        }
    }

    #[test]
    fn scope_containment_matches_the_manifest_algorithm() {
        assert!(path_is_within_scope("/", "/m"));
        assert!(path_is_within_scope("/m", "/m"));
        assert!(path_is_within_scope("/m", "/m/settings"));
        assert!(!path_is_within_scope("/m/", "/mobile"));
        // The exact v1 defect (G6/R-16).
        assert!(!path_is_within_scope("/assets/", "/m"));
    }

    #[test]
    fn the_hash_heuristic_catches_asset_pipeline_urls_and_nothing_else() {
        assert!(contains_content_hash(
            "/assets/manifest-dxh1a2b3c4d5e6f708.json"
        ));
        assert!(!contains_content_hash(MANIFEST_PATH));
        assert!(!contains_content_hash(SERVICE_WORKER_PATH));
        assert!(!contains_content_hash("/icons/icon-512-maskable.png"));
    }

    #[test]
    fn the_service_worker_is_small_enough_to_ship_inline() {
        assert!(
            SERVICE_WORKER_JS.len() <= 6 * 1024,
            "sw.js is {} bytes, over the 6 KB budget",
            SERVICE_WORKER_JS.len()
        );
    }
}
